script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=${CXX} -DCMAKE_C_COMPILER=${CC} ..
  - make
  - make test

sudo: required
dist: trusty

matrix:
  include:
    - compiler: gcc
      os: osx
      before_script:
        - brew update
        - brew outdated cmake || brew upgrade cmake
      env: WITH_BOOST=1 HAS_MEMRCHR=0 CXX=g++
    - compiler: clang
      os: osx
      before_script:
        - brew update
        - brew outdated cmake || brew upgrade cmake
      env: WITH_BOOST=1 HAS_MEMRCHR=0 CXX=clang++
    - compiler: gcc
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - cmake
            - libboost-system-dev
            - libboost-filesystem-dev
      env: WITH_BOOST=1 CXX=g++-4.9
    - compiler: gcc
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - cmake
      env: CXX=g++-5
    - compiler: clang
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
            - cmake
            - libboost-system-dev
            - libboost-filesystem-dev
      env: WITH_BOOST=1 CXX=clang++-3.6
    - compiler: clang
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
            - cmake
            - libboost-system-dev
            - libboost-filesystem-dev
      env: WITH_BOOST=1 CXX=clang++-3.7
