language: cpp
compiler:
  - clang
  - gcc
os:
  - osx
script:
  - make && make unittest
after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info
  - lcov --list coverage.info
  - coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info

sudo: required
dist: trusty

matrix:
  include:
    - compiler: gcc
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - libboost-system-dev
            - libboost-filesystem-dev
            - libgtest-dev
      env: COMPILER=g++-4.9
    - compiler: gcc
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libboost-system-dev
            - libboost-filesystem-dev
            - libgtest-dev
      env: COMPILER=g++-5
    - compiler: clang
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
            - libboost-system-dev
            - libboost-filesystem-dev
            - libgtest-dev
      env: COMPILER=clang++-3.6
    - compiler: clang
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
            - libboost-system-dev
            - libboost-filesystem-dev
            - libgtest-dev
      env: COMPILER=clang++-3.7
