script:
  - make -j

sudo: required
dist: trusty

matrix:
  include:
    - compiler: gcc
      os: osx
      env: USE_BOOST=1 HAS_MEMRCHR=0 CXX=g++
    - compiler: clang
      os: osx
      env: USE_BOOST=1 HAS_MEMRCHR=0 CXX=clang++
    - compiler: gcc
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - libboost-system-dev
            - libboost-filesystem-dev
            - libgtest-dev
      env: USE_BOOST=1 CXX=g++-4.9
    - compiler: gcc
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libgtest-dev
      env: CXX=g++-5
    - compiler: clang
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
            - libboost-system-dev
            - libboost-filesystem-dev
            - libgtest-dev
      env: USE_BOOST=1 CXX=clang++-3.6
    - compiler: clang
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
            - libboost-system-dev
            - libboost-filesystem-dev
            - libgtest-dev
      env: USE_BOOST=1 CXX=clang++-3.7
